In [2]:
import numpy as np

# data processing
import pandas as pd


# data visualization
import seaborn as sns
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style

# Algorithms
from sklearn.tree import DecisionTreeClassifier

In [3]:
data_train = pd.read_csv('../data/train.csv')
data_test = pd.read_csv('../data/test.csv')
data_gender = pd.read_csv('../data/gender_submission.csv')

In [4]:
data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
alldata = [data_train, data_test]

In [7]:
data_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
# data_train.corr()

In [9]:
data_train.columns.values

array(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype=object)

In [10]:
data_train.columns.values.shape

(12,)

In [11]:
data_train['Embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

In [12]:
data_train['Embarked'].isna().sum()

2

In [13]:
common_value = 'S'

for dataset in alldata:
    dataset['Embarked'] = dataset['Embarked'].fillna(common_value)

In [14]:
data_train['Embarked'].isna().sum()

0

In [15]:
for dataset in alldata:
    dataset['Fare'] = dataset['Fare'].fillna(0)
    dataset['Fare'] = dataset['Fare'].astype(int)

In [16]:
genders = {'male': 0, 'female': 1}

for dataset in alldata:
    dataset['Sex'] = dataset['Sex'].map(genders)

In [17]:
ports = {"S": 0, "C": 1, "Q": 2}

for dataset in alldata:
    dataset['Embarked'] = dataset['Embarked'].map(ports)

In [18]:
data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7,NaN,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71,C85,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7,NaN,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53,C123,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8,NaN,0

In [19]:
data_train = data_train.drop(['PassengerId','Name','Ticket','Cabin','Fare'], axis=1)
data_test  = data_test.drop(['PassengerId','Name','Ticket','Cabin','Fare'], axis=1)

In [20]:
data_train.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    0  22.0      1      0         0
1         1       1    1  38.0      1      0         1
2         1       3    1  26.0      0      0         0
3         1       1    1  35.0      1      0         0
4         0       3    0  35.0      0      0         0

In [21]:
data_test.head()

   Pclass  Sex   Age  SibSp  Parch  Embarked
0       3    0  34.5      0      0         2
1       3    1  47.0      1      0         0
2       2    0  62.0      0      0         2
3       3    0  27.0      0      0         0
4       3    1  22.0      1      1         0

In [22]:
data_test.insert(loc=0, column='Survived', value=data_gender['Survived'].values)

In [23]:
data_test.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    0  34.5      0      0         2
1         1       3    1  47.0      1      0         0
2         0       2    0  62.0      0      0         2
3         0       3    0  27.0      0      0         0
4         1       3    1  22.0      1      1         0

In [24]:
data_test.shape

(418, 7)

In [25]:
data_train['Age'].isna().sum()

177

In [26]:
np.random.seed(0)

In [27]:
mean = data_train["Age"].mean()
std = data_train["Age"].std()
list_isna = data_train['Age'].isna()
for line in range(list_isna.shape[0]):
    if(list_isna[line]==True):
      #print("Antes",line,data_train.iloc[line]["Age"])
      rand_age = np.random.randint(mean - std, mean + std, 1)
      #print(rand_age)
      data_train.at[line,'Age']=rand_age
      #print("Depois",line,data_train.iloc[line]["Age"])

In [28]:

data_train["Age"].isnull().sum()

0

In [29]:
data_test["Age"].isnull().sum()

86

In [30]:
mean = data_test["Age"].mean()
std = data_test["Age"].std()
list_isna = data_test['Age'].isna()
for line in range(list_isna.shape[0]):
    if(list_isna[line]==True):
      #print("Antes",line,data_test.iloc[line]["Age"])
      rand_age = np.random.randint(mean - std, mean + std, 1)
      #print(rand_age)
      data_test.at[line,'Age']=rand_age
      #print("Depois",line,data_test.iloc[line]["Age"])

In [31]:
data_test["Age"].isnull().sum()

0

In [32]:
data_train.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    0  22.0      1      0         0
1         1       1    1  38.0      1      0         1
2         1       3    1  26.0      0      0         0
3         1       1    1  35.0      1      0         0
4         0       3    0  35.0      0      0         0

In [33]:
data_train["Age"] = data_train["Age"].astype(int)
data_test["Age"] = data_test["Age"].astype(int)

In [34]:
X = data_train.drop(['Age'], axis=1).values
Y = data_train['Age'].values

In [35]:
#https://mljar.com/blog/visualize-decision-tree/

In [36]:
attributes = data_train.columns.values.tolist()
del attributes[0]
print(attributes)

#decisoes = np.unique(data_train['Survived'].values).tolist()
#print(decisoes)
#decisoes = map(str, decisoes)
#print(decisoes)
decisoes = ['0','1']

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked']

In [37]:
# X_test = data_test.values
# Y_pred = clf.predict(X_test)

In [38]:
# Y_test = data_gender['Survived'].values
# print(Y_test)

In [39]:
#from sklearn.metrics import accuracy_score

#accuracy_score(Y_test, Y_pred)

In [40]:
#from sklearn.metrics import balanced_accuracy_score
#balanced_accuracy_score(Y_test, Y_pred)

In [41]:
data_train.columns.values

array(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Embarked'],
      dtype=object)

In [42]:
data_train.drop(['Survived'], axis=1).values

array([[ 3,  0, 22,  1,  0,  0],
       [ 1,  1, 38,  1,  0,  1],
       [ 3,  1, 26,  0,  0,  0],
       ...,
       [ 3,  1, 34,  1,  2,  0],
       [ 1,  0, 26,  0,  0,  1],
       [ 3,  0, 32,  0,  0,  2]])

In [43]:
data_train['Survived'].values

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [44]:
aux = np.where(data_gender['Survived'].values==0)[0]
aux.shape

(266,)

In [45]:
data_gender.shape

(418, 2)

In [46]:
data_gender.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [47]:
data_test['Survived'] = data_gender['Survived']

In [48]:
data_test.head()

   Survived  Pclass  Sex  Age  SibSp  Parch  Embarked
0         0       3    0   34      0      0         2
1         1       3    1   47      1      0         0
2         0       2    0   62      0      0         2
3         0       3    0   27      0      0         0
4         1       3    1   22      1      1         0

In [49]:
data_test.corr()

          Survived    Pclass       Sex       Age     SibSp     Parch  Embarked
Survived  1.000000 -0.108615  1.000000 -0.003778  0.099943  0.159120  0.126779
Pclass   -0.108615  1.000000 -0.108615 -0.430290  0.001087  0.018721  0.031096
Sex       1.000000 -0.108615  1.000000 -0.003778  0.099943  0.159120  0.126779
Age      -0.003778 -0.430290 -0.003778  1.000000 -0.067480 -0.050601  0.057969
SibSp     0.099943  0.001087  0.099943 -0.067480  1.000000  0.306895 -0.100603
Parch     0.159120  0.018721  0.159120 -0.050601  0.306895  1.000000 -0.125164
Embarked  0.126779  0.031096  0.126779  0.057969 -0.100603 -0.125164  1.000000

In [50]:
# 1- juntar todos os dados em apenas uma planilha;
# 2- separar os dados em k-folds, onde k=5;
# 3- realizar tarefa de regressão de AGE utilizando modelos lineares;
# 4- Utilizar as medidas de avaliação MSE, MAE e MAPE, guardando numa lista cada valor de k para cada medida;
# 5- Criar gráficos de barras ou candlestick com média e desvio padrão de cada medida;
# 6- Repetir mesmos passos 1--5 para o algoritmo de árvores de decisão;

In [51]:
full_data = pd.concat([data_train, data_test])
full_data.shape

(1309, 7)

In [52]:
nulos = np.where(full_data['Age'].values==0)
print(nulos)
full_data.values[nulos,3] = 1

(array([  78,  305,  469,  644,  755,  803,  831, 1092, 1141, 1172, 1198,
       1245]),)

In [53]:
np.where(full_data['Age'].values==0)

(array([  78,  305,  469,  644,  755,  803,  831, 1092, 1141, 1172, 1198,
        1245]),)

In [54]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5,random_state=0,shuffle=True)

In [55]:
for i, (train_index, test_index) in enumerate(kf.split(full_data)):
  print(f"Fold {i}:")
  print(f"  Train Size={train_index.shape}")
  print(f"  Test Size={test_index.shape}")
  print(f"  Train: index={train_index}")
  print(f"  Test:  index={test_index}")

  Y_train = full_data.values[train_index][:,3]
  X_train = full_data.values[train_index]
  X_train = np.delete(X_train, 3, 1)


  Y_test = full_data.values[test_index][:,3]
  X_test = full_data.values[test_index]
  X_test = np.delete(X_test, 3, 1)

Fold 0:
  Train Size=(1047,)
  Test Size=(262,)
  Train: index=[   0    2    3 ... 1304 1306 1307]
  Test:  index=[   1    5    8    9   14   18   27   31   34   39   45   47   49   52
   55   58   61   75   80   85   92  108  124  140  141  142  152  156
  159  161  184  186  192  194  198  202  204  211  215  224  227  231
  233  240  241  247  251  254  268  270  276  283  295  298  299  302
  303  310  312  317  319  320  328  330  342  349  358  359  361  381
  386  390  393  397  406  408  412  416  418  420  422  425  426  427
  434  435  436  438  442  443  445  446  453  458  459  461  466  472
  474  477  478  482  483  486  491  503  505  506  511  512  513  523
  528  531  533  535  539  541  549  554  557  569  571  589  597  601
  608  609  610  618  625  632  638  641  642  649  651  656  658  669
  678  693  695  717  725  733  743  753  759  760  762  768  769  772
  773  785  790  792  793  794  795  796  798  813  814  817  833  839
  846  853  857  858  874  875  878  880  887  898  911  916  918  924
  934  938  942  948  960  961  965  968  969  977  988  991  995  996
 1000 1002 1005 1012 1015 1019 1028 1030 1041 1042 1046 1047 1050 1051
 1052 1075 1078 1087 1089 1090 1093 1095 1098 1100 1103 1117 1122 1124
 1125 1128 1135 1139 1145 1146 1149 1150 1166 1168 1179 1183 1189 1191
 1192 1197 1198 1200 1208 1209 1213 1215 1236 1239 1240 1243 1244 1251
 1256 1258 1260 1279 1287 1291 1299 1302 1305 1308]
Fold 1:
  Train Size=(1047,)
  Test Size=(262,)
  Train: index=[   0    1    3 ... 1305 1307 1308]
  Test:  index=[   2   10   15   16   19   30   40   44   54   60   64   65   70   77
   79   81   82   88   97  101  103  110  113  117  122  131  165  175
  182  183  187  188  190  191  195  196  200  206  214  230  239  249
  252  253  255  260  261  263  264  267  269  271  272  278  279  294
  308  311  315  316  322  333  338  351  356  362  363  364  366  367
  384  395  399  402  405  431  432  440  452  464  465  467  471  479
  481  487  489  494  495  500  501  517  520  526  529  530  536  540
  548  553  565  567  568  574  575  579  580  581  587  588  590  592
  613  615  619  629  644  646  655  657  668  672  674  682  686  687
  688  692  703  708  716  722  724  726  731  740  742  747  748  754
  761  764  775  780  783  784  787  789  799  805  808  811  815  818
  822  824  828  840  862  863  877  883  891  892  893  895  900  901
  905  914  921  922  923  930  933  936  940  946  947  955  958  970
  971  974  975  981  982  985  987  990  993  997  998 1003 1008 1013
 1023 1027 1034 1036 1039 1048 1072 1073 1076 1079 1080 1084 1092 1099
 1102 1105 1110 1114 1115 1118 1129 1130 1137 1140 1142 1148 1156 1157
 1158 1164 1174 1178 1181 1188 1193 1194 1203 1205 1206 1217 1221 1225
 1232 1241 1247 1249 1252 1253 1254 1255 1257 1259 1265 1267 1268 1270
 1271 1273 1278 1280 1281 1284 1292 1295 1298 1306]
Fold 2:
  Train Size=(1047,)
  Test Size=(262,)
  Train: index=[   0    1    2 ... 1305 1306 1308]
  Test:  index=[   6   12   17   20   21   35   37   38   42   46   48   50   62   66
   68   71   76   78   83   90   95  100  105  109  114  116  118  119
  120  125  127  133  138  143  144  145  150  154  155  157  158  162
  167  170  171  172  177  178  179  181  193  208  210  217  220  222
  229  235  236  238  242  243  250  258  262  266  285  288  289  293
  301  304  306  309  313  318  321  325  331  332  334  337  344  345
  346  350  352  372  378  379  380  382  385  389  391  396  403  409
  410  413  415  421  424  439  447  451  456  457  462  484  485  492
  493  496  507  515  521  522  524  527  545  546  552  561  564  576
  578  582  583  593  596  604  605  614  616  621  622  624  626  627
  630  634  652  654  660  661  662  664  665  667  671  677  681  689
  699  700  704  709  711  712  713  723  728  729  737  741  744  746
  751  752  757  758  766  771  801  829  830  831  834  848  864  866
  867  869  871  881  884  899  902  907  912  920  926  927  935  937
  943  950  953  959  963  966  980  983  986  992  994  999 1001 1009
 1014 1021 1024 1026 1045 1054 1056 1059 1064 1069 1070 1081 1108 1109
 1111 1112 1132 1133 1138 1147 1151 1153 1154 1160 1161 1162 1165 1170
 1173 1182 1190 1195 1202 1210 1212 1218 1222 1223 1227 1230 1231 1234
 1246 1264 1269 1283 1285 1293 1294 1296 1301 1307]
Fold 3:
  Train Size=(1047,)
  Test Size=(262,)
  Train: index=[   1    2    5 ... 1306 1307 1308]
  Test:  index=[   0    3    4    7   13   22   26   29   51   53   56   59   63   74
   89   96  102  104  107  112  126  132  134  135  137  147  148  153
  160  163  173  185  205  213  218  219  223  225  226  228  237  245
  246  248  259  265  280  281  282  284  292  300  305  326  327  336
  339  343  347  348  353  354  355  357  360  365  369  371  374  375
  376  392  394  400  401  404  407  411  414  417  419  428  437  441
  449  454  455  460  463  468  470  473  475  476  490  497  499  502
  504  516  518  519  532  534  538  542  550  558  563  566  570  572
  573  577  584  585  586  595  602  603  612  620  631  635  636  640
  643  647  648  650  653  666  670  676  679  680  683  685  690  691
  694  698  702  706  707  715  718  720  721  732  736  738  745  776
  781  786  788  800  810  819  820  823  825  826  827  832  836  837
  838  841  842  844  847  851  852  854  855  856  861  870  873  879
  890  896  897  903  904  906  913  915  929  932  939  941  944  945
  951  957  962  979  984  989 1006 1010 1011 1016 1017 1018 1025 1029
 1031 1032 1037 1038 1044 1049 1055 1057 1058 1061 1062 1063 1074 1083
 1086 1088 1096 1097 1101 1107 1113 1116 1120 1121 1123 1126 1127 1136
 1159 1163 1175 1177 1180 1185 1196 1219 1220 1224 1226 1229 1233 1235
 1237 1238 1261 1266 1275 1277 1282 1288 1290 1303]
Fold 4:
  Train Size=(1048,)
  Test Size=(261,)
  Train: index=[   0    1    2 ... 1306 1307 1308]
  Test:  index=[  11   23   24   25   28   32   33   36   41   43   57   67   69   72
   73   84   86   87   91   93   94   98   99  106  111  115  121  123
  128  129  130  136  139  146  149  151  164  166  168  169  174  176
  180  189  197  199  201  203  207  209  212  216  221  232  234  244
  256  257  273  274  275  277  286  287  290  291  296  297  307  314
  323  324  329  335  340  341  368  370  373  377  383  387  388  398
  423  429  430  433  444  448  450  469  480  488  498  508  509  510
  514  525  537  543  544  547  551  555  556  559  560  562  591  594
  598  599  600  606  607  611  617  623  628  633  637  639  645  659
  663  673  675  684  696  697  701  705  710  714  719  727  730  734
  735  739  749  750  755  756  763  765  767  770  774  777  778  779
  782  791  797  802  803  804  806  807  809  812  816  821  835  843
  845  849  850  859  860  865  868  872  876  882  885  886  888  889
  894  908  909  910  917  919  925  928  931  949  952  954  956  964
  967  972  973  976  978 1004 1007 1020 1022 1033 1035 1040 1043 1053
 1060 1065 1066 1067 1068 1071 1077 1082 1085 1091 1094 1104 1106 1119
 1131 1134 1141 1143 1144 1152 1155 1167 1169 1171 1172 1176 1184 1186
 1187 1199 1201 1204 1207 1211 1214 1216 1228 1242 1245 1248 1250 1262
 1263 1272 1274 1276 1286 1289 1297 1300 1304]

In [57]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)

reg.fit(X_train, Y_train)

reg.predict([[1, 1]])

[[0 3 0 1 0 0]
 [1 1 1 1 0 1]
 [1 3 1 0 0 0]
 ...
 [0 3 0 0 0 0]
 [0 3 0 0 0 0]
 [0 3 0 1 1 1]]
[22 38 26 ... 38 27 16]

ValueError: X has 2 features, but Lasso is expecting 6 features as input.